#!/usr/bin/env node

var gitHook;
try {
    gitHook = require(process.env.HOME + '/npm/lib/node_modules/grunt-x-web-git-hooks/lib/git-hook');
}
catch (e) {
    console.log('\x1B[31mUnable to load pre-commit hook!\x1B[39m')
    process.exit(0);
}

try {
    require('../../package.json')
}
catch (e) {
    process.exit(0);
}
gitHook('pre-commit', ['npm test']);
