#!/usr/bin/env python
import sys
try:
    from flake8.run import git_hook
except ImportError:
    print("You need to `pip install flake8`")
    sys.exit(0)

COMPLEXITY = 10
STRICT = True

if __name__ == '__main__':
    sys.exit(git_hook(complexity=COMPLEXITY, strict=STRICT, ignore='E501'))
